# Generated by Django 3.2.3 on 2021-05-26 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_tutorial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
