# Generated by Django 3.2.3 on 2021-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to=''),
        ),
    ]
